sudo: required
language: go
go:
  - "1.9.x"
services:
  - docker

notifications:
  email: false

env:
  global:
    - SKEEMA_TEST_IMAGES="mysql:5.5,mysql:5.6"

before_install:
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
  - go get github.com/golang/dep/cmd/dep

install:
  - dep ensure

script:
  - go test -v -coverprofile=coverage.out -covermode=count
  - go vet
  - test -z "$(gofmt -s -d *.go 2>&1)"
  - golint -set_exit_status

after_script:
  - goveralls -coverprofile=coverage.out -service=travis-ci
